[package]
name = "advent_of_code_2021"
version = "0.1.0"
edition = "2018"
authors = ["Russ Cam"]
description = "Advent of Code 2021 solutions"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
once_cell = "1"